In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

**FILTRAR ARRAY POR CONDICIONES**

In [3]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [8]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [10]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [12]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)