## APRENDIENDO NUMPY

es una librería de Python especializada en el cálculo numérico y el análisis de datos

In [4]:
import numpy as np

## PRIMEROS PASOS

In [6]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## CREANDO MATRIZ DE DATOS

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## TIPOS DE DATOS

In [10]:
arr= np.array([1,2,3,4],dtype='float64')
arr.dtype

dtype('float64')

## CAMBIAR TIPO DE DATOS

In [11]:
arr= np.array([0,1,2,3,4])
arr.dtype

dtype('int64')

In [12]:
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

## DIMENSIONES

### SCALAR

In [13]:
scalar = np.array(40)
print(scalar)
scalar.ndim

40


0

### VECTORES

In [14]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

### MATRICES

In [17]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

### TENSOR

In [18]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3