## APRENDIENDO NUMPY

es una librería de Python especializada en el cálculo numérico y el análisis de datos

In [4]:
import numpy as np

## PRIMEROS PASOS

In [6]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## CREANDO MATRIZ DE DATOS

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## TIPOS DE DATOS

In [10]:
arr= np.array([1,2,3,4],dtype='float64')
arr.dtype

dtype('float64')

## CAMBIAR TIPO DE DATOS

In [11]:
arr= np.array([0,1,2,3,4])
arr.dtype

dtype('int64')

In [12]:
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

## DIMENSIONES

### SCALAR

In [13]:
scalar = np.array(40)
print(scalar)
scalar.ndim

40


0

### VECTORES

In [14]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

### MATRICES

In [17]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

### TENSOR

In [18]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## CREACIÓN DE ARRAYS

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

DATOS ALEATORIOS

In [24]:
np.random.rand()

0.5694775384803971

In [30]:
aleatorio = np.random.rand(4,4)
aleatorio

array([[0.88871604, 0.89793128, 0.21929356, 0.91973341],
       [0.6479163 , 0.16437105, 0.3869221 , 0.34699969],
       [0.9205161 , 0.01283704, 0.85823827, 0.91148781],
       [0.41563882, 0.39218769, 0.988534  , 0.81756573]])

In [34]:
np.random.randint(1,15)

12

In [35]:
np.random.randint(1,100,(10,10))

array([[91, 21, 76, 20, 62, 82, 89, 57, 81, 56],
       [89, 39,  8,  8, 51, 83, 14, 46, 11, 90],
       [22, 28, 53, 96, 48, 20, 97, 10, 91, 85],
       [72, 40, 85, 93, 45, 58, 79, 66, 51, 66],
       [76, 24, 66, 99, 64, 14, 56, 32, 32, 15],
       [37, 19, 31, 87, 15, 90, 29, 67,  5, 20],
       [37,  3, 37, 88, 66,  3, 92, 44, 28,  7],
       [84, 62,  9, 32, 34, 49, 27, 29, 14, 78],
       [37, 26, 66, 89, 93, 79, 97,  9, 42, 82],
       [95, 92,  7, 98, 62, 62, 77, 57, 48, 88]])

## SHAPE Y RESHAPE

In [39]:
arr = np.random.randint(1,10,(3,2))
arr.shape
arr

array([[4, 3],
       [9, 4],
       [5, 6]])

In [40]:
arr.reshape(1,6)

array([[4, 3, 9, 4, 5, 6]])

## FUNCIONES MAS COMUNES

In [42]:
arr = np.random.randint(1,20,10)
arr

array([ 2, 13, 18,  3, 17, 11, 14, 18,  1, 19])

In [43]:
matriz = arr.reshape(2,5)
matriz

array([[ 2, 13, 18,  3, 17],
       [11, 14, 18,  1, 19]])

In [44]:
arr.max()

19

In [46]:
matriz.max(0)

array([11, 14, 18,  3, 19])

In [47]:
arr.min()

1

In [48]:
matriz.min(0)

array([ 2, 13, 18,  1, 17])

In [49]:
np.median(arr)

13.5

In [50]:
np.std(arr)

6.726068688320095

In [51]:
np.var(arr)

45.24

In [52]:
np.mean(arr)

11.6

In [56]:
matriz

array([[ 2, 13, 18,  3, 17],
       [11, 14, 18,  1, 19]])

In [57]:
matriz.shape

(2, 5)

In [59]:
matriz_t = matriz.T
matriz_t

array([[ 2, 11],
       [13, 14],
       [18, 18],
       [ 3,  1],
       [17, 19]])

In [60]:
matriz_t.shape

(5, 2)

## CONDICIONES O FILTROS

In [61]:
arr = np.linspace(1,10,10,dtype='int64')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
indices_cond  = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8])

In [67]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99])

## OPERACIONES

In [69]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
1 / arr

<ipython-input-72-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## OPERACIONES ENTRE ARRAYS

In [75]:
arr2 = arr.copy()
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [76]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [78]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
print(matriz)
print(matriz2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [79]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [80]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [82]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])