**PRIMEROS PASOS CON NUMPY**



1.   iMPORTAMOS LA LIBRERIA




In [1]:
import numpy as np




2.   CONVIERTIENDO LISTAS EN ARRAYS DE NUMPY




In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista
type(lista)

list

In [5]:
#convertir a lista en array de numpy
arr = np.array(lista)
arr
type(arr)

numpy.ndarray



3.   CREAMOS MATRICES



In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr[1]

2

In [11]:
matriz[1]

array([4, 5, 6])

In [12]:
matriz[0,2]

3



4.   Slicing




In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [15]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[-3:]

array([7, 8, 9])

In [17]:
matriz[1:,0]

array([4, 7])