In [1]:
import numpy as np

ARANGE

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

ZEROS

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

ONES

In [5]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

LINSPACE

In [6]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

EYE

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

RANDOM

In [11]:
np.random.rand()

0.4470950682752812

In [12]:
np.random.rand(4)

array([0.33896319, 0.71102954, 0.82308428, 0.79637561])

In [13]:
np.random.rand(4,4)

array([[0.59992067, 0.46531027, 0.96785512, 0.01333747],
       [0.80874844, 0.5765533 , 0.6395045 , 0.81605221],
       [0.60950957, 0.92087075, 0.34270718, 0.28545115],
       [0.35667897, 0.24705295, 0.19650025, 0.49586279]])

In [14]:
np.random.randint(1,100,(10,10))

array([[ 1, 58, 65, 41, 90, 99, 31, 66, 12, 89],
       [75, 55, 92, 58, 27, 96,  8, 79, 12, 57],
       [85,  6, 76,  2, 43,  8, 18, 46,  5, 63],
       [29, 15, 35, 97, 14, 23, 10, 72, 89, 73],
       [88, 65, 87, 43, 90, 57, 91, 63, 35, 43],
       [81, 86, 87, 47, 28,  7, 19, 23, 95, 18],
       [54, 10, 35, 43, 60, 63, 62, 41, 45, 79],
       [77, 92, 48, 46,  5, 78, 28, 81, 57, 97],
       [48, 41,  3, 29, 88,  2,  5, 80, 21, 66],
       [71, 12, 57, 26, 90, 52, 98,  5, 71, 37]])