In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)
arr

array([ 1, 10,  1,  8, 17, 11,  1,  3, 16, 10])

In [3]:
matriz = arr.reshape(2,5)
matriz

array([[ 1, 10,  1,  8, 17],
       [11,  1,  3, 16, 10]])

MAX y ARGMAX

In [4]:
arr.max()

17

In [7]:
matriz.max(1)

array([17, 16])

In [8]:
arr.argmax()

4

MIN Y ARGMIN

In [9]:
arr.argmin()

0

In [10]:
arr.min()

1

In [11]:
matriz.min(0)

array([ 1,  1,  1,  8, 10])

In [12]:
matriz.argmin(1)

array([0, 1])

PTP

In [13]:
arr

array([ 1, 10,  1,  8, 17, 11,  1,  3, 16, 10])

In [15]:
print(f"maximo : {arr.max()} - minimo : {arr.min()}")
arr.ptp()

maximo : 17 - minimo : 1


16

In [16]:
matriz.ptp(0)

array([10,  9,  2,  8,  7])

SORT

In [17]:
arr

array([ 1, 10,  1,  8, 17, 11,  1,  3, 16, 10])

In [20]:
arr.sort()
arr

array([ 1,  1,  1,  3,  8, 10, 10, 11, 16, 17])

PERCENTILE

In [22]:
np.percentile(arr,0)

1.0

MEDIAN

In [23]:
np.median(arr)

9.0

In [24]:
np.median(matriz,1)

array([ 1., 11.])

DESVIACIÓN STANDARD(STD)

In [27]:
np.std(arr)**2

33.36

VARIANZA(var)

In [26]:
np.var(arr)

33.36